export const EMOJIS = [
	{ value: '🌲', name: 'Evergreen Tree' },
	{ value: '🍎', name: 'Red Apple' },
	{ value: '🚗', name: 'Car' },
	{ value: '🌍', name: 'Earth Globe Europe-Africa' },
	{ value: '⚽', name: 'Soccer Ball' },
	{ value: '📚', name: 'Books' },
	{ value: '🎸', name: 'Guitar' },
	{ value: '💡', name: 'Light Bulb' },
	{ value: '🔥', name: 'Fire' },
	{ value: '🎨', name: 'Artist Palette' },
	{ value: '🌟', name: 'Glowing Star' },
	{ value: '✨', name: 'Sparks' },
	{ value: '⏰', name: 'Alarm Clock' },
	{ value: '🎁', name: 'Wrapped Gift' },
	{ value: '🍕', name: 'Pizza' },
	{ value: '🎧', name: 'Headphone' },
	{ value: '🚀', name: 'Rocket' },
	{ value: '📱', name: 'Mobile Phone' },
	{ value: '🏠', name: 'House' },
	{ value: '✈️', name: 'Airplane' },
	{ value: '🛳️', name: 'Passenger Ship' },
	{ value: '🌈', name: 'Rainbow' },
	{ value: '🛒', name: 'Shopping Cart' },
	{ value: '🥛', name: 'Milk' },
	{ value: '🍞', name: 'Bread' },
	{ value: '🎂', name: 'Birthday Cake' },
	{ value: '🍪', name: 'Cookie' },
	{ value: '🏀', name: 'Basketball' },
	{ value: '📷', name: 'Camera' },
	{ value: '🎻', name: 'Violin' },
	{ value: '🔑', name: 'Key' },
	{ value: '🗝️', name: 'Old Key' },
	{ value: '📦', name: 'Package' },
	{ value: '🏝️', name: 'Desert Island' },
	{ value: '🚉', name: 'Train Station' },
	{ value: '🚤', name: 'Speedboat' },
	{ value: '💎', name: 'Gem Stone' },
	{ value: '🧩', name: 'Puzzle Piece' },
	{ value: '🛠️', name: 'Hammer and Wrench' },
	{ value: '📀', name: 'DVD' },
	{ value: '🎲', name: 'Game Die' },
	{ value: '🛏️', name: 'Bed' },
	{ value: '🚪', name: 'Door' },
	{ value: '🖼️', name: 'Framed Picture' },
	{ value: '🛁', name: 'Bathtub' },
	{ value: '🗿', name: 'Moai' },
	{ value: '🌋', name: 'Volcano' },
	{ value: '🌌', name: 'Milky Way' },
	{ value: '🌅', name: 'Sunrise' },
	{ value: '⛰️', name: 'Mountain' },
	{ value: '🏖️', name: 'Beach with Umbrella' },
	{ value: '🌉', name: 'Bridge at Night' },
	{ value: '🎡', name: 'Ferris Wheel' },
	{ value: '🎢', name: 'Roller Coaster' },
	{ value: '🎳', name: 'Bowling' },
	{ value: '🎭', name: 'Performing Arts' },
	{ value: '🧪', name: 'Test Tube' },
	{ value: '🔭', name: 'Telescope' },
	{ value: '🎤', name: 'Microphone' },
	{ value: '📮', name: 'Postbox' },
	{ value: '📈', name: 'Chart Increasing' },
	{ value: '💼', name: 'Briefcase' },
	{ value: '🔒', name: 'Locked' },
	{ value: '✅', name: 'Check' }
] as const;

export const DEFAULT_EMOJI = EMOJIS[EMOJIS.length - 1].value!;
